---
# tasks file for first-role

- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: Installing python 
  apt:
   name: python3
   state: latest

- name: Install pip3
  apt:
   name: python3-pip
   state: latest
